### ISSUE TITLE
Request failed with status code 403

### ISSUE THREAD

**Issue by Container-Zero** [jingming295/koishi-plugin-nazrin-video-bilibili#1]
平台为`red`。
`bilibili-login`已配置完成，`cookie`刷新成功未报错。
发送`nazrin -v xxx`可以检索出视频列表，但当输入视频序号后，bot无输出，且控制台报错如下：
```
nazrin-video-bilibili AxiosError: Request failed with status code 403
at settle (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\axios\dist\node\axios.cjs:1967:12)
at IncomingMessage.handleStreamEnd (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\axios\dist\node\axios.cjs:3062:11)
at IncomingMessage.emit (node:events:526:35)
at endReadableNT (node:internal/streams/readable:1408:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by jingming295** [comment]
0059e414ead7573fe8441bd4dc9ee24b1d32a6d5 修复了拿不到视频直链的问题

**Comment by jingming295** [comment]
> 最新的更新修复了这个问题

0059e414ead7573fe8441bd4dc9ee24b1d32a6d5

**Comment by jingming295** [comment]
@BSTluo 这里还有个问题是bot无输出

**Comment by BSTluo** [comment]
ok)

**Comment by jingming295** [comment]
@BSTluo 
目前发现`red`适配器也许不支持官方的video标签，并且qq官方的video标签似乎也并不支持超过一定时长的视频/音频，并且red也早已停止维护 #[red](https://github.com/Hoshinonyaruko/mytest)
解决方案：
- [x] 让用户选择直接输出视频直链
- [x] 跳转第三方播放器
- [x] 跳转第三方平台进行观看

**Comment by BSTluo** [comment]
@Container-Zero 佬！你选择哪个（（

**Comment by Duhuan101** [comment]
> @Container-Zero 佬！你选择哪个（（

遇到了同样问题，我觉得可以第二个））
